Script started on 2020-02-12 21:24:13-0500
]0;rjv59@gold01: ~/Desktop/CS214/CS214Code/CS214/labs/lab02[01;32mrjv59@gold01[00m:[01;34m~/Desktop/CS214/CS214Code/CS214/labs/lab02[00m$ cat example6.lex exampl e6.y
%{
#include <stdio.h>
#include <stdlib.h>           /* atoi() */
#include <string.h>           /* strcmp() */
#include "example6.tab.h"
%}
%%
[0-9]+                  yylval = atoi(yytext); return NUMBER;
heat                    return TOKHEAT;
on|off                  yylval = !strcmp(yytext,"on"); return STATE;
set                     return TOKSET;
temperature             return TOKTEMPERATURE;
humidity                return TOKHUMIDITY;
\n                      /* ignore end of line */;
[ \t]+                  /* ignore whitespace */;
%%%{
#include <stdio.h>
#include <string.h>

/* declarations */
int yylex (void);
void yyerror (char const *);
int yyparse(void);

/* definitions */ 
void yyerror(const char *str) {
        fprintf(stderr,"error: %s\n",str);
}
 
int yywrap() {
        return 1;
} 
 
int main() {
        yyparse();
} 

%}

%token NUMBER TOKHEAT STATE TOKSET TOKTEMPERATURE TOKHUMIDITY
%%

commands: /* empty */
        | commands command
        ;

command:
        heat_switch
        | temperature_set
        | humidity_set
        ;

heat_switch:
        TOKHEAT STATE
        {
                if ($2) {  /* if STATE == 1 */
                        printf("\tHeat turned on\n");
                } else {
                        printf("\tHeat turned off\n");
                }
        }
        ;

temperature_set: 
        TOKSET TOKTEMPERATURE NUMBER
        {
                printf("\tTemperature set to %d\n",$3);
        }
        ;

humidity_set:
        TOKSET TOKHUMIDITY NUMBER
        {
                printf("\tHumidity set to %d\n",$3);
        }
        ;]0;rjv59@gold01: ~/Desktop/CS214/CS214Code/CS214/labs/lab02[01;32mrjv59@gold01[00m:[01;34m~/Desktop/CS214/CS214Code/CS214/labs/lab02[00m$ [Ke flex example6.lex
]0;rjv59@gold01: ~/Desktop/CS214/CS214Code/CS214/labs/lab02[01;32mrjv59@gold01[00m:[01;34m~/Desktop/CS214/CS214Code/CS214/labs/lab02[00m$ bison example6        -d example6.y
]0;rjv59@gold01: ~/Desktop/CS214/CS214Code/CS214/labs/lab02[01;32mrjv59@gold01[00m:[01;34m~/Desktop/CS214/CS214Code/CS214/labs/lab02[00m$ gcc lex.yy.c example6.t ab.c -o example6
]0;rjv59@gold01: ~/Desktop/CS214/CS214Code/CS214/labs/lab02[01;32mrjv59@gold01[00m:[01;34m~/Desktop/CS214/CS214Code/CS214/labs/lab02[00m$ [K./example6
heat on
	Heat turned on
heat off
	Heat turned off
set temperature 75
	Temperature set to 75
set humidity 25
	Humidity set to 25
]0;rjv59@gold01: ~/Desktop/CS214/CS214Code/CS214/labs/lab02[01;32mrjv59@gold01[00m:[01;34m~/Desktop/CS214/CS214Code/CS214/labs/lab02[00m$ exit

Script done on 2020-02-12 21:26:35-0500
